### ISSUE TITLE
npm  run build giving me the following errors 

### ISSUE THREAD

**Issue by monaldmuck** [adrianhajdin/3D_portfolio#8]
> 3d_portfolio@0.0.0 build
> vite build

error during build:
SyntaxError: Invalid regular expression: /(?<![\p{L}\p{N}_$]|(?<!\.\.)\.)(process\.env\.NODE_ENV|global\.process\.env\.NODE_ENV|globalThis\.process\.env\.NODE_ENV|__vite_process_env_NODE_ENV|import\.meta\.hot|import\.meta\.env\.VITE_APP_EMAILJS_SERVICE_ID|import\.meta\.env\.VITE_APP_EMAILJS_TEMPLATE_ID|import\.meta\.env\.VITE_APP_EMAILJS_PUBLIC\-KEY|import\.meta\.env\.BASE_URL|import\.meta\.env\.MODE|import\.meta\.env\.DEV|import\.meta\.env\.PROD|import\.meta\.env\.SSR|import\.meta\.env\.|import\.meta\.env|process\.env\.|global\.process\.env\.|globalThis\.process\.env\.)(?:(?<=\.)|(?![\p{L}\p{N}_$]|\s*?=[^=]))/: Invalid escape
    at new RegExp (<anonymous>)
    at generatePattern (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:42973:15)
    at definePlugin (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:42984:28)
    at resolvePlugins (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43675:9)
    at async resolveConfig (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66017:24)
    at async build (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47926:20)
    at async CAC.<anonymous> (file:///Users/ace/Desktop/3d_portfolio/node_modules/vite/dist/node/cli.js:842:9)

**Comment by monaldmuck** [comment]
my error
